/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query CarById($id: ID!) {\n    product(id: $id, idType: DATABASE_ID) {\n      id\n      databaseId\n      name\n      date\n      productCategories {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productTags {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productsfields {\n        model\n        version\n        yearmodel\n        mileage\n        transmission\n        fuel\n        color\n        featured\n        features {\n          name\n        }\n      }\n      ... on SimpleProduct {\n        onSale\n        stockStatus\n        price\n        rawPrice: price(format: RAW)\n        regularPrice\n        salePrice\n        stockStatus\n        stockQuantity\n        soldIndividually\n      }\n      image {\n        sourceUrl\n      }\n      galleryImages {\n        nodes {\n          sourceUrl\n        }\n      }\n    }\n  }\n": typeof types.CarByIdDocument,
    "\n  query ProductsPaginated($first: Int!, $after: String) {\n    products(first: $first, after: $after) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        cursor\n        node {\n          id\n          databaseId\n          name\n          date\n          productCategories {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productTags {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productBrands {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productsfields {\n            model\n            version\n            yearmodel\n            mileage\n            transmission\n            fuel\n            color\n            featured\n            features {\n              name\n            }\n          }\n          ... on SimpleProduct {\n            onSale\n            stockStatus\n            price\n            rawPrice: price(format: RAW)\n            regularPrice\n            salePrice\n            stockStatus\n            stockQuantity\n            soldIndividually\n          }\n          image {\n            sourceUrl\n          }\n\n          galleryImages {\n            nodes {\n              sourceUrl\n            }\n          }\n        }\n      }\n    }\n  }\n": typeof types.ProductsPaginatedDocument,
};
const documents: Documents = {
    "\n  query CarById($id: ID!) {\n    product(id: $id, idType: DATABASE_ID) {\n      id\n      databaseId\n      name\n      date\n      productCategories {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productTags {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productsfields {\n        model\n        version\n        yearmodel\n        mileage\n        transmission\n        fuel\n        color\n        featured\n        features {\n          name\n        }\n      }\n      ... on SimpleProduct {\n        onSale\n        stockStatus\n        price\n        rawPrice: price(format: RAW)\n        regularPrice\n        salePrice\n        stockStatus\n        stockQuantity\n        soldIndividually\n      }\n      image {\n        sourceUrl\n      }\n      galleryImages {\n        nodes {\n          sourceUrl\n        }\n      }\n    }\n  }\n": types.CarByIdDocument,
    "\n  query ProductsPaginated($first: Int!, $after: String) {\n    products(first: $first, after: $after) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        cursor\n        node {\n          id\n          databaseId\n          name\n          date\n          productCategories {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productTags {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productBrands {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productsfields {\n            model\n            version\n            yearmodel\n            mileage\n            transmission\n            fuel\n            color\n            featured\n            features {\n              name\n            }\n          }\n          ... on SimpleProduct {\n            onSale\n            stockStatus\n            price\n            rawPrice: price(format: RAW)\n            regularPrice\n            salePrice\n            stockStatus\n            stockQuantity\n            soldIndividually\n          }\n          image {\n            sourceUrl\n          }\n\n          galleryImages {\n            nodes {\n              sourceUrl\n            }\n          }\n        }\n      }\n    }\n  }\n": types.ProductsPaginatedDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CarById($id: ID!) {\n    product(id: $id, idType: DATABASE_ID) {\n      id\n      databaseId\n      name\n      date\n      productCategories {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productTags {\n        edges {\n          node {\n            name\n          }\n        }\n      }\n      productsfields {\n        model\n        version\n        yearmodel\n        mileage\n        transmission\n        fuel\n        color\n        featured\n        features {\n          name\n        }\n      }\n      ... on SimpleProduct {\n        onSale\n        stockStatus\n        price\n        rawPrice: price(format: RAW)\n        regularPrice\n        salePrice\n        stockStatus\n        stockQuantity\n        soldIndividually\n      }\n      image {\n        sourceUrl\n      }\n      galleryImages {\n        nodes {\n          sourceUrl\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').CarByIdDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductsPaginated($first: Int!, $after: String) {\n    products(first: $first, after: $after) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        cursor\n        node {\n          id\n          databaseId\n          name\n          date\n          productCategories {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productTags {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productBrands {\n            edges {\n              node {\n                name\n              }\n            }\n          }\n          productsfields {\n            model\n            version\n            yearmodel\n            mileage\n            transmission\n            fuel\n            color\n            featured\n            features {\n              name\n            }\n          }\n          ... on SimpleProduct {\n            onSale\n            stockStatus\n            price\n            rawPrice: price(format: RAW)\n            regularPrice\n            salePrice\n            stockStatus\n            stockQuantity\n            soldIndividually\n          }\n          image {\n            sourceUrl\n          }\n\n          galleryImages {\n            nodes {\n              sourceUrl\n            }\n          }\n        }\n      }\n    }\n  }\n"): typeof import('./graphql').ProductsPaginatedDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
