/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversoRouteImport } from './routes/universo'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as EsportesRouteImport } from './routes/esportes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const UniversoRoute = UniversoRouteImport.update({
  id: '/universo',
  path: '/universo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportesRoute = EsportesRouteImport.update({
  id: '/esportes',
  path: '/esportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/esportes': typeof EsportesRoute
  '/loja': typeof LojaRoute
  '/modelos': typeof ModelosRoute
  '/universo': typeof UniversoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/esportes': typeof EsportesRoute
  '/loja': typeof LojaRoute
  '/modelos': typeof ModelosRoute
  '/universo': typeof UniversoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/esportes': typeof EsportesRoute
  '/loja': typeof LojaRoute
  '/modelos': typeof ModelosRoute
  '/universo': typeof UniversoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/esportes' | '/loja' | '/modelos' | '/universo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/esportes' | '/loja' | '/modelos' | '/universo'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/esportes'
    | '/loja'
    | '/modelos'
    | '/universo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EsportesRoute: typeof EsportesRoute
  LojaRoute: typeof LojaRoute
  ModelosRoute: typeof ModelosRoute
  UniversoRoute: typeof UniversoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universo': {
      id: '/universo'
      path: '/universo'
      fullPath: '/universo'
      preLoaderRoute: typeof UniversoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esportes': {
      id: '/esportes'
      path: '/esportes'
      fullPath: '/esportes'
      preLoaderRoute: typeof EsportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EsportesRoute: EsportesRoute,
  LojaRoute: LojaRoute,
  ModelosRoute: ModelosRoute,
  UniversoRoute: UniversoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
