/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstoqueVehicleIdRouteImport } from './routes/estoque.$vehicleId'

const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueVehicleIdRoute = EstoqueVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => EstoqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/localizacao': typeof LocalizacaoRoute
  '/estoque/$vehicleId': typeof EstoqueVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/localizacao': typeof LocalizacaoRoute
  '/estoque/$vehicleId': typeof EstoqueVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/localizacao': typeof LocalizacaoRoute
  '/estoque/$vehicleId': typeof EstoqueVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/delivery'
    | '/estoque'
    | '/localizacao'
    | '/estoque/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/delivery'
    | '/estoque'
    | '/localizacao'
    | '/estoque/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/delivery'
    | '/estoque'
    | '/localizacao'
    | '/estoque/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  DeliveryRoute: typeof DeliveryRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  LocalizacaoRoute: typeof LocalizacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/$vehicleId': {
      id: '/estoque/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/estoque/$vehicleId'
      preLoaderRoute: typeof EstoqueVehicleIdRouteImport
      parentRoute: typeof EstoqueRoute
    }
  }
}

interface EstoqueRouteChildren {
  EstoqueVehicleIdRoute: typeof EstoqueVehicleIdRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueVehicleIdRoute: EstoqueVehicleIdRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  DeliveryRoute: DeliveryRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  LocalizacaoRoute: LocalizacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
